In [1]:
import tensorflow as tf  # tensorflow 
import numpy as np       ## numpy packages
from sklearn.model_selection import cross_val_score  ## for cross validation
from sklearn.preprocessing import OneHotEncoder    #3 for encoding
from sklearn.utils import shuffle  ## shiffle the data
from sklearn import preprocessing
import os
import pandas as pd
from datetime import datetime as dt
import logging ## for logging the data
from sklearn import datasets


In [2]:
## load the dataaet
iris = datasets.load_iris()

In [3]:
## fetching the feature matrix and the target
X = np.asarray(iris.data,'float32')
Y = iris.target

In [4]:
## preproces the data
X = preprocessing.scale(X)

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:172: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:189: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "


In [5]:
min_max_scaler = preprocessing.MinMaxScaler()


In [6]:
X = min_max_scaler.fit_transform(X) ## this is actually normalization

In [7]:
## convert to binary
lb = preprocessing.LabelBinarizer()

In [8]:
Y = lb.fit_transform(iris.target)

In [9]:
print (Y)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 

In [10]:
from sklearn.model_selection import train_test_split
##train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3)


In [11]:
print (x_train)

[[0.1388889  0.5833334  0.15254238 0.0416666 ]
 [0.30555555 0.79166675 0.05084744 0.12499997]
 [0.11111102 0.50000006 0.05084744 0.0416666 ]
 [0.41666672 0.24999997 0.5084746  0.4583333 ]
 [0.8055555  0.4166667  0.8135593  0.625     ]
 [0.1944444  0.6666666  0.06779659 0.0416666 ]
 [0.6666666  0.5416667  0.7966101  0.83333325]
 [0.83333343 0.37500006 0.89830506 0.70833325]
 [0.86111116 0.3333333  0.8644067  0.75      ]
 [0.6111111  0.3333333  0.6101695  0.5833333 ]
 [0.1944444  0.5416667  0.06779659 0.0416666 ]
 [0.49999997 0.3333333  0.5084746  0.49999994]
 [0.7777778  0.4166667  0.8305085  0.83333325]
 [0.4722222  0.37500006 0.59322035 0.5833333 ]
 [0.24999993 0.875      0.08474576 0.        ]
 [0.08333325 0.50000006 0.06779659 0.0416666 ]
 [0.22222216 0.5833334  0.08474576 0.0416666 ]
 [0.08333325 0.6666666  0.         0.0416666 ]
 [0.8055555  0.50000006 0.8474576  0.70833325]
 [0.69444454 0.4166667  0.7627119  0.83333325]
 [0.3333333  0.16666672 0.47457626 0.41666666]
 [0.24999993 

## model creation by scratch

In [12]:
## first create the placeholder
X = tf.placeholder('float',[None,4]) ## we feed a lot of data and its dimanesion is 4
Y = tf.placeholder('float',[None,3]) ## we feed a lot of data and its dimanesion is 3

In [13]:
## init the weight
def init_weights(shape):
    return tf.Variable(tf.random_normal(shape))


In [14]:
w_h = init_weights([4,4]) ## this is the primary variable
w_o = init_weights([4,3])  ## this is another layer and this is the 
## final layer so thats why it has 4 input and output 3 cause the target is 3

In [15]:
def model(X,w_h,w_o):
    h = tf.nn.sigmoid(tf.matmul(X,w_h))
    return tf.matmul(h,w_o)

In [16]:
## make the model
model_output= model(X,w_h,w_o)

In [17]:
## cost function create apply the softmax on the out put with the given value 
## it can find the cost
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = model_output, labels=Y))

In [18]:
## train operation
lr = 0.01
train_op = tf.train.GradientDescentOptimizer(lr).minimize(cost)

In [19]:
## predict the value of  with argmax
tf.arg_max(model_output,1)

<tf.Tensor 'ArgMax:0' shape=(?,) dtype=int64>

In [20]:
sess = tf.Session()
init = tf.initialize_all_variables()
sess.run(init)

In [21]:
for i in range(500):
    for start,end in zip(range(len(x_train)),range(len(y_train))):
        sess.run(train_op,feed_dict={X:x_train[start:end],Y:y_train[start:end]})
        

In [22]:
sess.run(w_h)

array([[-1.6543439e-02,  8.7859201e-01, -9.2081124e-01, -1.9668156e+00],
       [ 5.6631930e-02,  1.6142329e-03,  8.7726903e-01,  9.8565966e-02],
       [ 9.1397661e-01, -8.2624143e-01,  2.1662190e+00, -1.6688812e-01],
       [ 2.0642612e+00, -8.4890157e-01,  2.0305133e+00,  6.7134249e-01]],
      dtype=float32)

In [23]:
sess.run(w_o)

array([[ 1.5654763 , -0.70778275,  0.574048  ],
       [-0.39527756,  0.37193772, -0.0313584 ],
       [-1.5393908 , -0.5079923 , -2.3383749 ],
       [-0.29803067, -1.6216406 , -0.7787286 ]], dtype=float32)